// gen_skills.h — GENERATED by tools/codegen.py from engine/data/spec/. DO NOT EDIT.
// spec-hash: 7eba72940493ad8d
#ifndef BB_GEN_SKILLS_H
#define BB_GEN_SKILLS_H

#include <stdint.h>

typedef enum {
    BB_CAT_GENERAL,
    BB_CAT_AGILITY,
    BB_CAT_STRENGTH,
    BB_CAT_PASSING,
    BB_CAT_MUTATION,
    BB_CAT_DEVIOUS,
    BB_CAT_COUNT
} bb_skill_cat;

typedef enum {
    BB_SK_CATCH,
    BB_SK_DIVING_CATCH,
    BB_SK_DIVING_TACKLE,
    BB_SK_DODGE,
    BB_SK_DEFENSIVE,
    BB_SK_HIT_AND_RUN,
    BB_SK_JUMP_UP,
    BB_SK_LEAP,
    BB_SK_SAFE_PAIR_OF_HANDS,
    BB_SK_SIDESTEP,
    BB_SK_SPRINT,
    BB_SK_SURE_FEET,
    BB_SK_DIRTY_PLAYER,
    BB_SK_EYE_GOUGE,
    BB_SK_FUMBLEROOSKI,
    BB_SK_LETHAL_FLIGHT,
    BB_SK_LONE_FOULER,
    BB_SK_PILE_DRIVER,
    BB_SK_PUT_THE_BOOT_IN,
    BB_SK_QUICK_FOUL,
    BB_SK_SABOTEUR,
    BB_SK_SHADOWING,
    BB_SK_SNEAKY_GIT,
    BB_SK_VIOLENT_INNOVATOR,
    BB_SK_BLOCK,
    BB_SK_DAUNTLESS,
    BB_SK_FEND,
    BB_SK_FRENZY,
    BB_SK_KICK,
    BB_SK_PRO,
    BB_SK_STEADY_FOOTING,
    BB_SK_STRIP_BALL,
    BB_SK_SURE_HANDS,
    BB_SK_TACKLE,
    BB_SK_TAUNT,
    BB_SK_WRESTLE,
    BB_SK_BIG_HAND,
    BB_SK_CLAWS,
    BB_SK_DISTURBING_PRESENCE,
    BB_SK_EXTRA_ARMS,
    BB_SK_FOUL_APPEARANCE,
    BB_SK_HORNS,
    BB_SK_IRON_HARD_SKIN,
    BB_SK_MONSTROUS_MOUTH,
    BB_SK_PREHENSILE_TAIL,
    BB_SK_TENTACLES,
    BB_SK_TWO_HEADS,
    BB_SK_VERY_LONG_LEGS,
    BB_SK_ACCURATE,
    BB_SK_CANNONEER,
    BB_SK_CLOUD_BURSTER,
    BB_SK_DUMP_OFF,
    BB_SK_GIVE_AND_GO,
    BB_SK_HAIL_MARY_PASS,
    BB_SK_LEADER,
    BB_SK_NERVES_OF_STEEL,
    BB_SK_ON_THE_BALL,
    BB_SK_PASS,
    BB_SK_PUNT,
    BB_SK_SAFE_PASS,
    BB_SK_ARM_BAR,
    BB_SK_BRAWLER,
    BB_SK_BREAK_TACKLE,
    BB_SK_BULLSEYE,
    BB_SK_GRAB,
    BB_SK_GUARD,
    BB_SK_JUGGERNAUT,
    BB_SK_MIGHTY_BLOW,
    BB_SK_MULTIPLE_BLOCK,
    BB_SK_STAND_FIRM,
    BB_SK_STRONG_ARM,
    BB_SK_THICK_SKULL,
    BB_SK_ALWAYS_HUNGRY,
    BB_SK_ANIMAL_SAVAGERY,
    BB_SK_ANIMOSITY,
    BB_SK_BALL_AND_CHAIN,
    BB_SK_BLOODLUST,
    BB_SK_BOMBARDIER,
    BB_SK_BONE_HEAD,
    BB_SK_BREATHE_FIRE,
    BB_SK_CHAINSAW,
    BB_SK_DECAY,
    BB_SK_DRUNKARD,
    BB_SK_HATRED,
    BB_SK_HYPNOTIC_GAZE,
    BB_SK_INSIGNIFICANT,
    BB_SK_KICK_TEAM_MATE,
    BB_SK_LONER,
    BB_SK_MY_BALL,
    BB_SK_NO_BALL,
    BB_SK_PICK_ME_UP,
    BB_SK_PLAGUE_RIDDEN,
    BB_SK_POGO,
    BB_SK_PROJECTILE_VOMIT,
    BB_SK_REALLY_STUPID,
    BB_SK_REGENERATION,
    BB_SK_RIGHT_STUFF,
    BB_SK_SECRET_WEAPON,
    BB_SK_STAB,
    BB_SK_STUNTY,
    BB_SK_SWOOP,
    BB_SK_TAKE_ROOT,
    BB_SK_THROW_TEAM_MATE,
    BB_SK_TIMMM_BER,
    BB_SK_TITCHY,
    BB_SK_TRICKSTER,
    BB_SK_UNCHANNELLED_FURY,
    BB_SK_UNSTEADY,
    BB_SKILL_COUNT
} bb_skill_id;

#define BB_NUM_SKILLS 72   // learnable skills; ids >= this are traits

typedef struct {
    const char* id;       // snake_case
    const char* display;
    uint8_t category;     // bb_skill_cat; 0xFF for traits
    uint8_t active;       // ACTIVE (1) / PASSIVE (0) per mirror annotation
    uint8_t compulsory;   // asterisk: use is compulsory
    uint8_t elite;
    int8_t value;         // default X parameter; -1 = none
    uint8_t is_trait;
} bb_skill_def;

extern const bb_skill_def bb_skill_defs[BB_SKILL_COUNT];

// Random-skill table per category. The 2D6 roll encodes a key 1..12:
// first D6 1-3 selects keys 1-6, 4-6 selects keys 7-12; second D6 = row.
// Index [cat][key-1] -> skill id.
extern const uint8_t bb_random_skill_table[BB_CAT_COUNT][12];

#endif // BB_GEN_SKILLS_H
