// gen_tables.h — GENERATED by tools/codegen.py from engine/data/spec/. DO NOT EDIT.
// spec-hash: 27029fe4285a6dae
#ifndef BB_GEN_TABLES_H
#define BB_GEN_TABLES_H

#include <stdint.h>

#define BB_INJ_STUN_MAX 7      // 2..N = stunned
#define BB_INJ_KO_MAX 9        // ..N = KO
#define BB_INJ_STUNTY_STUN_MAX 6
#define BB_INJ_STUNTY_KO_MAX 8
#define BB_INJ_STUNTY_BH_MAX 9 // stunty: badly hurt band

typedef enum {
    BB_CAS_BADLY_HURT = 0,
    BB_CAS_SERIOUSLY_HURT,
    BB_CAS_SERIOUS_INJURY,
    BB_CAS_LASTING_INJURY,
    BB_CAS_DEAD,
} bb_casualty;
// D16 -> bb_casualty
extern const uint8_t bb_casualty_table[17];

// Kickoff events: 2D6 -> event id
typedef enum {
    BB_KO_GET_THE_REF,
    BB_KO_TIME_OUT,
    BB_KO_SOLID_DEFENCE,
    BB_KO_HIGH_KICK,
    BB_KO_CHEERING_FANS,
    BB_KO_BRILLIANT_COACHING,
    BB_KO_CHANGING_WEATHER,
    BB_KO_QUICK_SNAP,
    BB_KO_CHARGE,
    BB_KO_DODGY_SNACK,
    BB_KO_PITCH_INVASION,
    BB_KO_EVENT_COUNT
} bb_kickoff_event;
extern const uint8_t bb_kickoff_table[13]; // index 2..12

// Weather: 2D6 -> bb_weather (bb_types.h)
extern const uint8_t bb_weather_table[13];

// Prayers to Nuffle: D16 -> prayer id
typedef enum {
    BB_PRAYER_TREACHEROUS_TRAPDOOR,
    BB_PRAYER_FRIENDS_WITH_THE_REF,
    BB_PRAYER_STILETTO,
    BB_PRAYER_IRON_MAN,
    BB_PRAYER_KNUCKLE_DUSTERS,
    BB_PRAYER_BAD_HABITS,
    BB_PRAYER_GREASY_CLEATS,
    BB_PRAYER_BLESSING_OF_NUFFLE,
    BB_PRAYER_MOLES_UNDER_THE_PITCH,
    BB_PRAYER_PERFECT_PASSING,
    BB_PRAYER_DAZZLING_CATCHING,
    BB_PRAYER_FAN_INTERACTION,
    BB_PRAYER_FOULING_FRENZY,
    BB_PRAYER_THROW_A_ROCK,
    BB_PRAYER_UNDER_SCRUTINY,
    BB_PRAYER_INTENSIVE_TRAINING,
    BB_PRAYER_COUNT
} bb_prayer;
extern const uint8_t bb_prayer_table[17];

#endif // BB_GEN_TABLES_H
