// gen_teams.h — GENERATED by tools/codegen.py from engine/data/spec/. DO NOT EDIT.
// spec-hash: 6f80e7cba73cd837
#ifndef BB_GEN_TEAMS_H
#define BB_GEN_TEAMS_H

#include "bb/gen_skills.h"

typedef enum {
    BB_TEAM_AMAZON,
    BB_TEAM_BLACK_ORC,
    BB_TEAM_BRETONNIAN,
    BB_TEAM_CHAOS_CHOSEN,
    BB_TEAM_CHAOS_DWARF,
    BB_TEAM_CHAOS_RENEGADES,
    BB_TEAM_DARK_ELF,
    BB_TEAM_DWARF,
    BB_TEAM_ELVEN_UNION,
    BB_TEAM_GNOME,
    BB_TEAM_GOBLIN,
    BB_TEAM_HALFLING,
    BB_TEAM_HIGH_ELF,
    BB_TEAM_HUMAN,
    BB_TEAM_IMPERIAL_NOBILITY,
    BB_TEAM_KHORNE,
    BB_TEAM_LIZARDMEN,
    BB_TEAM_NECROMANTIC_HORROR,
    BB_TEAM_NORSE,
    BB_TEAM_NURGLE,
    BB_TEAM_OGRE,
    BB_TEAM_OLD_WORLD_ALLIANCE,
    BB_TEAM_ORC,
    BB_TEAM_SHAMBLING_UNDEAD,
    BB_TEAM_SKAVEN,
    BB_TEAM_SNOTLING,
    BB_TEAM_TOMB_KINGS,
    BB_TEAM_UNDERWORLD_DENIZENS,
    BB_TEAM_VAMPIRE,
    BB_TEAM_WOOD_ELF,
    BB_TEAM_COUNT
} bb_team_id;

#define BB_MAX_POSITIONS 12  // Old World Alliance has 11
#define BB_POS_MAX_SKILLS 10

typedef struct {
    const char* display;
    uint8_t qty_min, qty_max;
    uint16_t cost_k;
    int8_t ma, st, ag, pa, av; // ag/pa/av target numbers; pa 0 = '-'
    uint8_t num_skills;
    uint8_t skills[BB_POS_MAX_SKILLS];      // bb_skill_id
    int8_t skill_values[BB_POS_MAX_SKILLS]; // X param per skill; -1 none
    uint8_t primary_mask;   // bit i = category i (bb_skill_cat)
    uint8_t secondary_mask;
    uint8_t big_guy;
} bb_position_def;

typedef struct {
    const char* id;
    const char* display;
    uint8_t tier;
    uint8_t reroll_cost_k;  // 50/60/70
    uint8_t apothecary;
    uint8_t num_positions;
    bb_position_def positions[BB_MAX_POSITIONS];
} bb_team_def;

extern const bb_team_def bb_team_defs[BB_TEAM_COUNT];

#endif // BB_GEN_TEAMS_H
