#!/usr/bin/env python3
"""Write the stage wrappers and CAMPAIGN_PLAN.json for the 2026-10-02 long run from one list (D407).

    python3 make_plan.py OUT_DIR      # OUT_DIR gets common_env.sh's siblings: sNN_<name>.sh and CAMPAIGN_PLAN.json

Stage 0 is a disposable 50M-step canary of chain 37's exact launch path. Stages 1 to 3 are the registered
restart-scale arms (chains 37, 38, 39). Stages 4 onward are the speculative continuation from chain 37 under the
discard rule in D407's amendment and are meant to be replaced by a registered plan.
"""
import json
import pathlib
import sys

CAMPAIGN = "longrun-20261002"
HOME = "/home/rache/longrun"
C = "/home/rache/bloodbowl-rl-longrun-20261002"
OLD = "/home/rache/bloodbowl-rl-qualification-candidate-10619e2"
POOL_C36 = "51a19cff01f7701e10a4aeeca842cfb398b30c461e09c13af158362afd51ab80"
POOL_C35 = "ff4c0552cb9e6b6a21a49c484a750958521391110a06c23c6f7904ad348660b1"
MARKER_C34 = f"{OLD}/runs/ladder-d0-r0chain34-cont30-rr1-20260916/LADDER_RUNG_COMPLETE.json"
MARKER_C30 = f"{OLD}/runs/ladder-d0-r0chain30-rr1-20260914/LADDER_RUNG_COMPLETE.json"
# Speculative rungs halt when the two-seed mean of offense AWAY champion touchdowns is below 0.536. The verdict
# tool fires only when all three clauses hold, so the per-seed floors are set where they always hold.
GUARD = {"EXAM_GUARD_FLOOR_S42": "9.0", "EXAM_GUARD_FLOOR_S43": "9.0", "EXAM_GUARD_FLOOR_MEAN": "0.536"}


def marker(stamp):
    return f"{C}/runs/ladder-d0-{stamp}/LADDER_RUNG_COMPLETE.json"


STAGES = [
    dict(name="s00_canary", stamp="canary37-lr05-from34-20261002", seed=42, prev=MARKER_C34,
         pool=POOL_C36, rule="none", extra={"STEPS": "50000000"}),
    dict(name="s01_chain37", stamp="r0chain37-lr05-from34-20261002", seed=42, prev=MARKER_C34,
         pool=POOL_C36, rule="none"),
    dict(name="s02_chain38", stamp="r0chain38-lr05-from30-s44-20261002", seed=44, prev=MARKER_C30,
         pool=POOL_C35, rule="none"),
    dict(name="s03_chain39", stamp="r0chain39-lr05-from30-s42-20261002", seed=42, prev=MARKER_C30,
         pool=POOL_C35, rule="none"),
]
previous = "r0chain37-lr05-from34-20261002"
for number in range(40, 46):
    stamp = f"r0chain{number}-lr05-cont{previous.split('-')[0].replace('r0chain', '')}-20261002"
    STAGES.append(dict(name=f"s{number - 36:02d}_chain{number}", stamp=stamp, seed=42,
                       prev=marker(previous), pool=None, rule="drift-guard", extra=dict(GUARD)))
    previous = stamp


def wrapper(stage):
    lines = ["#!/usr/bin/env bash",
             f"# Stage {stage['name']} of campaign {CAMPAIGN} (D407). Generated by make_plan.py; edit the list there.",
             "set -uo pipefail",
             f"source {HOME}/common_env.sh",
             f"export SEED={stage['seed']} STAMP={stage['stamp']}",
             f"export PREV_COMPLETE={stage['prev']}",
             "export LADDER_CHAIN_LR_SCALE=0.5 LADDER_CHAIN_ENT_SCALE=2.0",
             f"export EXAM_RULE={stage['rule']}"]
    if stage.get("pool"):
        lines.append(f"export EXPECTED_POOL_HASH={stage['pool']}")
    for key, value in (stage.get("extra") or {}).items():
        lines.append(f"export {key}={value}")
    lines.append('exec bash "$C/tools/chain_stage.sh"')
    return "\n".join(lines) + "\n"


def main():
    out = pathlib.Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    stamps = [stage["stamp"] for stage in STAGES]
    assert len(set(stamps)) == len(stamps), "duplicate STAMP"
    plan = {"schema_version": 1, "campaign_id": CAMPAIGN, "root": C,
            "trainer_pgrep": "[p]uffer_cuda_runtime.py train|[p]uffer train|[c]hain_stage.sh|"
                             "[l]adder_stage.sh|[r]un_reward_screen.sh|[e]val_vs_contact_bot.sh",
            "stages": []}
    for stage in STAGES:
        path = out / f"{stage['name']}.sh"
        path.write_text(wrapper(stage))
        path.chmod(0o755)
        plan["stages"].append({
            "name": stage["name"], "launch": f"bash {HOME}/{stage['name']}.sh",
            "success": f"runs/ladder-d0-{stage['stamp']}/EXAM_VERDICT_PASS.json",
            "progress": f"runs/ladder-d0-{stage['stamp']}/SCREEN_STATUS.json",
            "max_attempts": 3, "max_stale_seconds": 6000})
    (out / "CAMPAIGN_PLAN.json").write_text(json.dumps(plan, indent=2) + "\n")
    for stage in STAGES:
        print(stage["name"], stage["stamp"], "<-", stage["prev"].split("/runs/")[1].split("/")[0], stage["rule"])


if __name__ == "__main__":
    main()
