#ifndef BBE_F5_TRAINABILITY_H
#define BBE_F5_TRAINABILITY_H

/*
 * Sealed F5 qualification role.
 *
 * bloodbowl.h includes this file only after Bloodbowl, bb_match, the engine
 * compatibility fingerprint, and the state-bank SHA-256 implementation are
 * available.  The ordinary role compiles only inert helpers.  The dedicated
 * role compiles the reviewed raw match bytes and may replace exactly the
 * match-selection portion of reset; it remains state-bank kind NONE.
 */

/*
 * Legacy/test state-bank build headers predate the qualification namespace.
 * Absence can only mean disabled/none.  An enabled role, by contrast, must
 * provide the complete identity below and therefore still fails closed at
 * compile time when any role macro is absent.
 */
#ifndef PUFFER_QUALIFICATION_FIXTURE_ENABLED
#define PUFFER_QUALIFICATION_FIXTURE_ENABLED 0
#endif
#ifndef PUFFER_QUALIFICATION_FIXTURE_ROLE
#if PUFFER_QUALIFICATION_FIXTURE_ENABLED
#error "enabled qualification fixture is missing its role identity"
#else
#define PUFFER_QUALIFICATION_FIXTURE_ROLE "none"
#endif
#endif

#if PUFFER_QUALIFICATION_FIXTURE_ENABLED

#include "f5_trainability_fixture.generated.h"

_Static_assert(PUFFER_QUALIFICATION_FIXTURE_ENABLED == 1,
               "F5 qualification role must be exactly enabled");
_Static_assert(PUFFER_QUALIFICATION_FIXTURE_QUALIFICATION_ONLY == 1,
               "F5 fixture must be qualification-only");
_Static_assert(PUFFER_STATE_BANK_COMPILED_KIND == BBE_STATE_BANK_NONE,
               "F5 qualification role must not compile a state bank");
_Static_assert(BBE_F5_TRAINABILITY_MATCH_BYTES_SIZE == sizeof(bb_match),
               "F5 raw match bytes do not match the local bb_match ABI");
_Static_assert(
    sizeof BBE_F5_TRAINABILITY_MATCH_BYTES ==
        BBE_F5_TRAINABILITY_MATCH_BYTES_SIZE,
    "F5 generated byte array has the wrong extent");

static int bbe_f5_trainability_abi_valid(void) {
    return sizeof(bb_match) == BBE_F5_TRAINABILITY_MATCH_BYTES_SIZE &&
        BBE_F5_TRAINABILITY_MATCH_BYTES_SIZE == 2240u &&
        BBE_F5_TRAINABILITY_FULL_BUNDLE_RECORDS == 26u &&
        BBE_F5_TRAINABILITY_FULL_BUNDLE_BYTES == 58568u &&
        BBE_F5_TRAINABILITY_F5_BBS_BYTES == 2268u &&
        bbe_state_fingerprint() ==
            BBE_F5_TRAINABILITY_ENGINE_FINGERPRINT &&
        BBE_F5_TRAINABILITY_ENGINE_FINGERPRINT == UINT32_C(0x64897CDE) &&
        BB_TEAM_COUNT == BBE_F5_TRAINABILITY_TEAM_COUNT &&
        BBE_F5_TRAINABILITY_TEAM_COUNT == 30u &&
        BB_SKILL_COUNT == BBE_F5_TRAINABILITY_SKILL_COUNT &&
        BBE_F5_TRAINABILITY_SKILL_COUNT == 108u &&
        BB_A_TYPE_COUNT == BBE_F5_TRAINABILITY_ACTION_TYPE_COUNT &&
        BBE_F5_TRAINABILITY_ACTION_TYPE_COUNT == 30u;
}

static int bbe_f5_trainability_identity_valid_uncached(void) {
    uint8_t digest[32];
    bbe_sha256_bytes(
        BBE_F5_TRAINABILITY_MATCH_BYTES,
        BBE_F5_TRAINABILITY_MATCH_BYTES_SIZE, digest);
    return bbe_f5_trainability_abi_valid() &&
        bbe_sha256_matches(
            digest, BBE_F5_TRAINABILITY_RAW_MATCH_SHA256) &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_ROLE,
               BBE_F5_TRAINABILITY_ROLE) == 0 &&
        strcmp(BBE_F5_TRAINABILITY_ROLE, "f5-fixed-state-v1") == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_SCHEMA,
               BBE_F5_TRAINABILITY_TASK_SCHEMA) == 0 &&
        strcmp(BBE_F5_TRAINABILITY_TASK_SCHEMA,
               "bloodbowl-trainability-task-v1") == 0 &&
        strcmp(BBE_F5_TRAINABILITY_FIXTURE_SCHEMA,
               "bloodbowl-f5-fixture-v1") == 0 &&
        strcmp(BBE_F5_TRAINABILITY_GENERATOR_SCHEMA,
               "bloodbowl-f5-foundation-generator-v1") == 0 &&
        strcmp(BBE_F5_TRAINABILITY_RULESET, "BB2025") == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_MATCH_SHA256,
               BBE_F5_TRAINABILITY_RAW_MATCH_SHA256) == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_BBS_SHA256,
               BBE_F5_TRAINABILITY_F5_BBS_SHA256) == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_BUNDLE_SHA256,
               BBE_F5_TRAINABILITY_FULL_BUNDLE_SHA256) == 0 &&
        PUFFER_QUALIFICATION_FIXTURE_BBS_SOURCE_ID ==
            BBE_F5_TRAINABILITY_PROOF_SOURCE_ID &&
        BBE_F5_TRAINABILITY_PROOF_SOURCE_ID ==
            UINT32_C(0xA9000019) &&
        PUFFER_QUALIFICATION_FIXTURE_AUTHORED_SOURCE_ID ==
            BBE_F5_TRAINABILITY_DURABLE_SOURCE_ID &&
        BBE_F5_TRAINABILITY_DURABLE_SOURCE_ID ==
            UINT32_C(0xAE00001A) &&
        BBE_F5_TRAINABILITY_TEMPLATE_ID == 5u &&
        BBE_F5_TRAINABILITY_RECIPE_REVISION == 1u &&
        BBE_F5_TRAINABILITY_CELL_ID == 1u &&
        BBE_F5_TRAINABILITY_VARIANT_ID == 1u &&
        BBE_F5_TRAINABILITY_VARIANT_SEED == 410u &&
        BBE_F5_TRAINABILITY_CAPTURE_ACTIONS == 51u &&
        BBE_F5_TRAINABILITY_CAPTURE_DICE == 19u &&
        PUFFER_QUALIFICATION_FIXTURE_MAX_DECISIONS ==
            BBE_F5_TRAINABILITY_MAX_DECISIONS &&
        BBE_F5_TRAINABILITY_MAX_DECISIONS == 8u &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_REWARD_CONTRACT,
               "touchdown-zero-sum-only-v1") == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_REFERENCE_TRACE_SCHEMA,
               BBE_F5_TRAINABILITY_REFERENCE_TRACE_SCHEMA) == 0 &&
        strcmp(BBE_F5_TRAINABILITY_REFERENCE_TRACE_SCHEMA,
               "bloodbowl-f5-reference-trace-v1") == 0 &&
        strcmp(PUFFER_QUALIFICATION_FIXTURE_REFERENCE_TRACE_SHA256,
               BBE_F5_TRAINABILITY_REFERENCE_TRACE_SHA256) == 0;
}

/*
 * The bytes and build macros are compile-time constants.  Qualification
 * horizons are only eight decisions, so hashing 2,240 bytes on every
 * autoreset would put an integrity check in the hot loop.  Reconcile once per
 * process with an atomic publication; racing initializer threads may perform
 * the same pure check, but all observe the same immutable verdict.
 */
static atomic_int bbe_f5_trainability_identity_status = ATOMIC_VAR_INIT(0);

static int bbe_f5_trainability_identity_valid(void) {
    int status = atomic_load_explicit(
        &bbe_f5_trainability_identity_status, memory_order_acquire);
    if (status != 0) return status > 0;
    int valid = bbe_f5_trainability_identity_valid_uncached();
    int expected = 0;
    atomic_compare_exchange_strong_explicit(
        &bbe_f5_trainability_identity_status, &expected,
        valid ? 1 : -1, memory_order_release, memory_order_relaxed);
    return valid;
}

static int bbe_f5_trainability_match_sha256_valid(const bb_match* match) {
    if (match == NULL) return 0;
    uint8_t digest[32];
    bbe_sha256_bytes(match, sizeof *match, digest);
    return bbe_sha256_matches(
        digest, PUFFER_QUALIFICATION_FIXTURE_MATCH_SHA256);
}

static int bbe_f5_trainability_copy_match(bb_match* output) {
    if (output == NULL || !bbe_f5_trainability_identity_valid()) return -1;
    memcpy(output, BBE_F5_TRAINABILITY_MATCH_BYTES, sizeof *output);
    return 0;
}

#else

static int bbe_f5_trainability_abi_valid(void) {
    return 0;
}

static int bbe_f5_trainability_identity_valid(void) {
    return strcmp(PUFFER_QUALIFICATION_FIXTURE_ROLE, "none") == 0;
}

static int bbe_f5_trainability_match_sha256_valid(const bb_match* match) {
    (void)match;
    return 0;
}

static int bbe_f5_trainability_copy_match(bb_match* output) {
    (void)output;
    return -1;
}

#endif

/*
 * Return the first semantic field that differs from the frozen F5 contract.
 * The strict binding calls this after its ordinary closed-schema parser and
 * before bank resolution, environment allocation, or RNG consumption.
 * Exact 0/1/-1 comparisons are intentional: every required value is exactly
 * representable in both the public double config and the applied C fields.
 */
static const char* bbe_f5_trainability_config_error_impl(
        const Bloodbowl* env, int require_base_seed) {
#if !PUFFER_QUALIFICATION_FIXTURE_ENABLED
    (void)env;
    (void)require_base_seed;
    return NULL;
#else
    if (env == NULL) return "environment";
    if (!bbe_f5_trainability_identity_valid()) {
        return "qualification_fixture_identity";
    }
#define BBE_F5_REQUIRE(field, expected) \
    do {                                \
        if (env->field != (expected)) return #field; \
    } while (0)
    if (require_base_seed && env->seed != UINT64_C(1)) return "seed";
    BBE_F5_REQUIRE(max_decisions, 8);
    BBE_F5_REQUIRE(macro_moves, 0);
    BBE_F5_REQUIRE(demo_reset_pct, 0.0f);
    BBE_F5_REQUIRE(state_bank_kind, BBE_STATE_BANK_NONE);
    BBE_F5_REQUIRE(demo_endzone_maxdist, 0);
    BBE_F5_REQUIRE(demo_pickup_maxdist, 0);
    BBE_F5_REQUIRE(demo_postkick_maxturn, 0);
    BBE_F5_REQUIRE(demo_pass_maxrange, 0);
    BBE_F5_REQUIRE(exclude_team, -1);
    BBE_F5_REQUIRE(force_home_team, -1);
    BBE_F5_REQUIRE(force_away_team, -1);
    BBE_F5_REQUIRE(scripted_opponent, 0);
    BBE_F5_REQUIRE(scripted_opponent_type, 0);
    BBE_F5_REQUIRE(scripted_opponent_team, BB_AWAY);
    BBE_F5_REQUIRE(skillup_max_players, 4);
    BBE_F5_REQUIRE(skillup_max_each, 2);
    BBE_F5_REQUIRE(skillup_secondary_pct, 0.0f);
    BBE_F5_REQUIRE(render_fps, 60);
    BBE_F5_REQUIRE(reward_configured, 1);
    BBE_F5_REQUIRE(reward_td, 1.0f);
    BBE_F5_REQUIRE(reward_win, 0.0f);
    BBE_F5_REQUIRE(reward_draw, 0.0f);
    BBE_F5_REQUIRE(reward_setup_done, 0.0f);
    BBE_F5_REQUIRE(reward_setup_autofix, 0.0f);
    BBE_F5_REQUIRE(reward_ball_gain, 0.0f);
    BBE_F5_REQUIRE(reward_ball_loss, 0.0f);
    BBE_F5_REQUIRE(reward_dist_ball, 0.0f);
    BBE_F5_REQUIRE(reward_dist_endzone, 0.0f);
    BBE_F5_REQUIRE(reward_dist_pbrs_gamma, 0.0f);
    BBE_F5_REQUIRE(reward_injury_inflicted, 0.0f);
    BBE_F5_REQUIRE(reward_injury_taken, 0.0f);
    BBE_F5_REQUIRE(reward_injury_value_scaled, 0);
    BBE_F5_REQUIRE(reward_send_off, 0.0f);
    BBE_F5_REQUIRE(reward_kickoff_touchback, 0.0f);
    BBE_F5_REQUIRE(reward_surf_taken, 0.0f);
    BBE_F5_REQUIRE(reward_surf_inflicted, 0.0f);
    BBE_F5_REQUIRE(reward_k_kd, 0.0f);
    BBE_F5_REQUIRE(reward_k_value, 0.0f);
    BBE_F5_REQUIRE(reward_k_self_injury, 0.0f);
    BBE_F5_REQUIRE(reward_k_ball, 0.0f);
    BBE_F5_REQUIRE(reward_k_seq, 0.0f);
    BBE_F5_REQUIRE(reward_k_turnover, 0.0f);
    BBE_F5_REQUIRE(reward_possession, 0.0f);
    BBE_F5_REQUIRE(reward_k_assist, 0.0f);
    BBE_F5_REQUIRE(reward_rush_cost, 0.0f);
    BBE_F5_REQUIRE(reward_carrier_exposure, 0.0f);
    BBE_F5_REQUIRE(reward_carrier_exposure_soft, 0.0f);
    BBE_F5_REQUIRE(reward_carrier_threat, 0.0f);
    BBE_F5_REQUIRE(reward_defensive_threat, 0.0f);
    BBE_F5_REQUIRE(reward_defensive_threat_soft, 0.0f);
    BBE_F5_REQUIRE(reward_statmatch_scale, 0.0f);
#undef BBE_F5_REQUIRE
    return NULL;
#endif
}

static const char* bbe_f5_trainability_config_error(
        const Bloodbowl* env) {
    return bbe_f5_trainability_config_error_impl(env, 1);
}

/*
 * The closed kwarg preflight above validates base seed=1 before vector
 * allocation. Puffer then derives the ordinary distinct stream
 * base_seed+environment_index. Reset must preserve that shared vectorization
 * behavior while continuing to recheck every other frozen runtime field.
 */
static const char* bbe_f5_trainability_runtime_config_error(
        const Bloodbowl* env) {
    return bbe_f5_trainability_config_error_impl(env, 0);
}

#endif
