#!/usr/bin/env python3
"""Compile engine/data/spec/*.yaml into C tables (gen_*.h / gen_*.c).

Usage: python3 tools/codegen.py [--check]
  --check  verify generated files are up to date (CI gate) without writing.

Generated files are checked in so the C engine builds with zero deps.
Ordering is stable (spec file order); ids are stable once assigned — append
only, never reorder, or replays/golden traces break.
"""
import argparse
import hashlib
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "engine" / "data" / "spec"
INC = ROOT / "engine" / "include" / "bb"
SRC = ROOT / "engine" / "src"

CATEGORIES = ["general", "agility", "strength", "passing", "mutation", "devious"]


def cident(s: str) -> str:
    out = []
    for ch in s:
        out.append(ch.upper() if (ch.isalnum()) else "_")
    ident = "".join(out)
    while "__" in ident:
        ident = ident.replace("__", "_")
    return ident.strip("_")


def load(name):
    p = SPEC / name
    with open(p) as f:
        return yaml.safe_load(f)


def header(tag: str, payload: str) -> str:
    h = hashlib.sha256(payload.encode()).hexdigest()[:16]
    return (
        f"// {tag} — GENERATED by tools/codegen.py from engine/data/spec/. DO NOT EDIT.\n"
        f"// spec-hash: {h}\n"
    )


def gen_skills(skills_doc):
    skills = skills_doc["skills"]
    traits = skills_doc["traits"]
    all_entries = [(s, False) for s in skills] + [(t, True) for t in traits]

    lines_h = []
    lines_h.append("#ifndef BB_GEN_SKILLS_H")
    lines_h.append("#define BB_GEN_SKILLS_H")
    lines_h.append("")
    lines_h.append("#include <stdint.h>")
    lines_h.append("")
    lines_h.append("typedef enum {")
    for cat in CATEGORIES:
        lines_h.append(f"    BB_CAT_{cident(cat)},")
    lines_h.append("    BB_CAT_COUNT")
    lines_h.append("} bb_skill_cat;")
    lines_h.append("")
    lines_h.append("typedef enum {")
    for e, _ in all_entries:
        lines_h.append(f"    BB_SK_{cident(e['name'])},")
    lines_h.append("    BB_SKILL_COUNT")
    lines_h.append("} bb_skill_id;")
    lines_h.append("")
    lines_h.append(f"#define BB_NUM_SKILLS {len(skills)}   // learnable skills; ids >= this are traits")
    lines_h.append("")
    lines_h.append("typedef struct {")
    lines_h.append("    const char* id;       // snake_case")
    lines_h.append("    const char* display;")
    lines_h.append("    uint8_t category;     // bb_skill_cat; 0xFF for traits")
    lines_h.append("    uint8_t active;       // ACTIVE (1) / PASSIVE (0) per mirror annotation")
    lines_h.append("    uint8_t compulsory;   // asterisk: use is compulsory")
    lines_h.append("    uint8_t elite;")
    lines_h.append("    int8_t value;         // default X parameter; -1 = none")
    lines_h.append("    uint8_t is_trait;")
    lines_h.append("} bb_skill_def;")
    lines_h.append("")
    lines_h.append("extern const bb_skill_def bb_skill_defs[BB_SKILL_COUNT];")
    lines_h.append("")
    lines_h.append("// Random-skill table per category. The 2D6 roll encodes a key 1..12:")
    lines_h.append("// first D6 1-3 selects keys 1-6, 4-6 selects keys 7-12; second D6 = row.")
    lines_h.append("// Index [cat][key-1] -> skill id.")
    lines_h.append("extern const uint8_t bb_random_skill_table[BB_CAT_COUNT][12];")
    lines_h.append("")
    lines_h.append("#endif // BB_GEN_SKILLS_H")

    lines_c = []
    lines_c.append('#include "bb/gen_skills.h"')
    lines_c.append("")
    lines_c.append("const bb_skill_def bb_skill_defs[BB_SKILL_COUNT] = {")
    for e, is_trait in all_entries:
        cat = "0xFF" if is_trait else f"BB_CAT_{cident(e['category'])}"
        active = 1 if e.get("mode") == "active" else 0
        comp = 1 if e.get("compulsory") else 0
        elite = 1 if e.get("elite") else 0
        value = e.get("value")
        value = -1 if value is None else int(value)
        lines_c.append(
            f'    {{"{e["name"]}", "{e["display"]}", {cat}, {active}, {comp}, {elite}, {value}, {1 if is_trait else 0}}},'
        )
    lines_c.append("};")
    lines_c.append("")

    rnd = skills_doc.get("random_table", {})
    lines_c.append("const uint8_t bb_random_skill_table[BB_CAT_COUNT][12] = {")
    for cat in CATEGORIES:
        row = rnd.get(cat, {})
        ids = []
        for key in range(1, 13):
            sk = row.get(key)
            if not sk:
                raise SystemExit(f"random_table missing {cat}[{key}]")
            ids.append(f"BB_SK_{cident(sk)}")
        lines_c.append(f"    {{{', '.join(ids)}}}, // {cat}")
    lines_c.append("};")

    return "\n".join(lines_h) + "\n", "\n".join(lines_c) + "\n", {e["name"] for e, _ in all_entries}


def skill_ref(name, known):
    """Map a spec skill reference (possibly {name, value}) to (id, numeric value).

    Values may be ints (Loner 4 -> 4) or keyword strings (Hatred 'troll',
    Animosity 'goblin'/'all'). Keyword params are stored as -1 here; the
    keyword semantics are handled by dedicated engine logic later (they gate
    WHO the skill applies to, not a dice number)."""
    if isinstance(name, dict):
        v = name.get("value")
        return name["name"], (int(v) if isinstance(v, int) else None)
    return name, None


def gen_teams(teams, known_skills):
    lines_h = []
    lines_h.append("#ifndef BB_GEN_TEAMS_H")
    lines_h.append("#define BB_GEN_TEAMS_H")
    lines_h.append("")
    lines_h.append('#include "bb/gen_skills.h"')
    lines_h.append("")
    lines_h.append("typedef enum {")
    for t in teams:
        lines_h.append(f"    BB_TEAM_{cident(t['name'])},")
    lines_h.append("    BB_TEAM_COUNT")
    lines_h.append("} bb_team_id;")
    lines_h.append("")
    lines_h.append("#define BB_MAX_POSITIONS 12  // Old World Alliance has 11")
    lines_h.append("#define BB_POS_MAX_SKILLS 10")
    lines_h.append("")
    lines_h.append("typedef struct {")
    lines_h.append("    const char* display;")
    lines_h.append("    uint8_t qty_min, qty_max;")
    lines_h.append("    uint16_t cost_k;")
    lines_h.append("    int8_t ma, st, ag, pa, av; // ag/pa/av target numbers; pa 0 = '-'")
    lines_h.append("    uint8_t num_skills;")
    lines_h.append("    uint8_t skills[BB_POS_MAX_SKILLS];      // bb_skill_id")
    lines_h.append("    int8_t skill_values[BB_POS_MAX_SKILLS]; // X param per skill; -1 none")
    lines_h.append("    uint8_t primary_mask;   // bit i = category i (bb_skill_cat)")
    lines_h.append("    uint8_t secondary_mask;")
    lines_h.append("    uint8_t big_guy;")
    lines_h.append("} bb_position_def;")
    lines_h.append("")
    lines_h.append("typedef struct {")
    lines_h.append("    const char* id;")
    lines_h.append("    const char* display;")
    lines_h.append("    uint8_t tier;")
    lines_h.append("    uint8_t reroll_cost_k;  // 50/60/70")
    lines_h.append("    uint8_t apothecary;")
    lines_h.append("    uint8_t num_positions;")
    lines_h.append("    bb_position_def positions[BB_MAX_POSITIONS];")
    lines_h.append("} bb_team_def;")
    lines_h.append("")
    lines_h.append("extern const bb_team_def bb_team_defs[BB_TEAM_COUNT];")
    lines_h.append("")
    lines_h.append("#endif // BB_GEN_TEAMS_H")

    lines_c = []
    lines_c.append('#include "bb/gen_teams.h"')
    lines_c.append("")
    lines_c.append("const bb_team_def bb_team_defs[BB_TEAM_COUNT] = {")
    for t in teams:
        positions = t["positions"]
        if len(positions) > 12:
            raise SystemExit(f"team {t['name']}: {len(positions)} positions > BB_MAX_POSITIONS")
        lines_c.append(f'    {{ // {t["display"]}')
        lines_c.append(f'        "{t["name"]}", "{t["display"]}", {t.get("tier", 0)}, {t["reroll_cost"]}, {1 if t.get("apothecary", True) else 0}, {len(positions)},')
        lines_c.append("        {")
        for p in positions:
            sk_ids, sk_vals = [], []
            for ref in p.get("skills", []):
                sid, val = skill_ref(ref, known_skills)
                if sid not in known_skills:
                    raise SystemExit(f"team {t['name']} position {p['name']}: unknown skill '{sid}'")
                sk_ids.append(f"BB_SK_{cident(sid)}")
                sk_vals.append(str(-1 if val is None else int(val)))
            n = len(sk_ids)
            if n > 10:
                raise SystemExit(f"position {p['name']}: too many skills ({n})")
            sk_ids += ["0"] * (10 - n)
            sk_vals += ["-1"] * (10 - n)
            pmask = 0
            for c in p.get("primary", []):
                pmask |= 1 << CATEGORIES.index(c)
            smask = 0
            for c in p.get("secondary", []):
                smask |= 1 << CATEGORIES.index(c)
            qmin, qmax = p["qty"]
            pa = p["pa"] if p["pa"] is not None else 0
            lines_c.append(
                f'            {{"{p["display"]}", {qmin}, {qmax}, {p["cost"]}, '
                f'{p["ma"]}, {p["st"]}, {p["ag"]}, {pa}, {p["av"]}, {n}, '
                f"{{{', '.join(sk_ids)}}}, {{{', '.join(sk_vals)}}}, "
                f"{pmask}, {smask}, {1 if p.get('big_guy') else 0}}},"
            )
        lines_c.append("        },")
        lines_c.append("    },")
    lines_c.append("};")
    return "\n".join(lines_h) + "\n", "\n".join(lines_c) + "\n"


def gen_tables(tables):
    lines_h = []
    lines_h.append("#ifndef BB_GEN_TABLES_H")
    lines_h.append("#define BB_GEN_TABLES_H")
    lines_h.append("")
    lines_h.append("#include <stdint.h>")
    lines_h.append("")
    # injury
    inj = tables["injury"]
    lines_h.append(f"#define BB_INJ_STUN_MAX {inj['stun'][1]}      // 2..N = stunned")
    lines_h.append(f"#define BB_INJ_KO_MAX {inj['ko'][1]}        // ..N = KO")
    inj_st = tables["injury_stunty"]
    lines_h.append(f"#define BB_INJ_STUNTY_STUN_MAX {inj_st['stun'][1]}")
    lines_h.append(f"#define BB_INJ_STUNTY_KO_MAX {inj_st['ko'][1]}")
    if "badly_hurt" in inj_st:
        lines_h.append(f"#define BB_INJ_STUNTY_BH_MAX {inj_st['badly_hurt'][1]} // stunty: badly hurt band")
    # casualty
    cas = tables["casualty"]
    lines_h.append("")
    lines_h.append("typedef enum {")
    lines_h.append("    BB_CAS_BADLY_HURT = 0,")
    lines_h.append("    BB_CAS_SERIOUSLY_HURT,")
    lines_h.append("    BB_CAS_SERIOUS_INJURY,")
    lines_h.append("    BB_CAS_LASTING_INJURY,")
    lines_h.append("    BB_CAS_DEAD,")
    lines_h.append("} bb_casualty;")
    lines_h.append("// D16 -> bb_casualty")
    lines_h.append("extern const uint8_t bb_casualty_table[17];")
    lines_h.append("")
    lines_h.append("// Kickoff events: 2D6 -> event id")
    lines_h.append("typedef enum {")
    seen = []
    for roll in sorted(tables["kickoff"]):
        ev = tables["kickoff"][roll]["event"]
        if ev not in seen:
            seen.append(ev)
    for ev in seen:
        lines_h.append(f"    BB_KO_{cident(ev)},")
    lines_h.append("    BB_KO_EVENT_COUNT")
    lines_h.append("} bb_kickoff_event;")
    lines_h.append("extern const uint8_t bb_kickoff_table[13]; // index 2..12")
    lines_h.append("")
    lines_h.append("// Weather: 2D6 -> bb_weather (bb_types.h)")
    lines_h.append("extern const uint8_t bb_weather_table[13];")
    lines_h.append("")
    lines_h.append("// Prayers to Nuffle: D16 -> prayer id")
    prayers = tables.get("prayers", {})
    if prayers:
        lines_h.append("typedef enum {")
        pseen = []
        for roll in sorted(prayers):
            pv = prayers[roll]
            name = pv["prayer"] if isinstance(pv, dict) else pv
            if name not in pseen:
                pseen.append(name)
        for p in pseen:
            lines_h.append(f"    BB_PRAYER_{cident(p)},")
        lines_h.append("    BB_PRAYER_COUNT")
        lines_h.append("} bb_prayer;")
        lines_h.append("extern const uint8_t bb_prayer_table[17];")
    lines_h.append("")
    lines_h.append("#endif // BB_GEN_TABLES_H")

    lines_c = []
    lines_c.append('#include "bb/gen_tables.h"')
    lines_c.append("")
    cas_rows = ["0"] * 17
    for name, key in [("badly_hurt", "BB_CAS_BADLY_HURT"), ("seriously_hurt", "BB_CAS_SERIOUSLY_HURT"),
                      ("serious_injury", "BB_CAS_SERIOUS_INJURY"), ("lasting_injury", "BB_CAS_LASTING_INJURY"),
                      ("dead", "BB_CAS_DEAD")]:
        lo, hi = cas[name]
        for r in range(lo, hi + 1):
            cas_rows[r] = key
    lines_c.append(f"const uint8_t bb_casualty_table[17] = {{{', '.join(cas_rows)}}};")
    lines_c.append("")
    ko_rows = ["0", "0"] + [f"BB_KO_{cident(tables['kickoff'][r]['event'])}" for r in range(2, 13)]
    lines_c.append(f"const uint8_t bb_kickoff_table[13] = {{{', '.join(ko_rows)}}};")
    lines_c.append("")
    WMAP = {"sweltering_heat": "0", "very_sunny": "1", "perfect_conditions": "2",
            "pouring_rain": "3", "blizzard": "4"}
    w = tables["weather"]

    def wname(entry):
        return entry if isinstance(entry, str) else entry.get("condition")

    w_rows = ["2", "2"]
    for r in range(2, 13):
        name = wname(w[r])
        if name not in WMAP:
            raise SystemExit(f"weather[{r}]: unknown condition '{name}'")
        w_rows.append(WMAP[name])
    lines_c.append(f"const uint8_t bb_weather_table[13] = {{{', '.join(w_rows)}}};")
    if prayers:
        pr_rows = ["0"]
        for r in range(1, 17):
            pv = prayers.get(r)
            name = (pv["prayer"] if isinstance(pv, dict) else pv) if pv else None
            pr_rows.append(f"BB_PRAYER_{cident(name)}" if name else "0")
        lines_c.append("")
        lines_c.append(f"const uint8_t bb_prayer_table[17] = {{{', '.join(pr_rows)}}};")
    return "\n".join(lines_h) + "\n", "\n".join(lines_c) + "\n"


def write_or_check(path: Path, content: str, check: bool, changed: list):
    tagged = header(path.name, content) + content
    if check:
        if not path.exists() or path.read_text() != tagged:
            changed.append(str(path))
    else:
        path.write_text(tagged)
        print(f"wrote {path.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    skills_doc = load("skills.yaml")
    teams = load("teams_a.yaml")["teams"] + load("teams_b.yaml")["teams"]
    tables = load("tables.yaml")

    changed = []
    skills_h, skills_c, known = gen_skills(skills_doc)
    write_or_check(INC / "gen_skills.h", skills_h, args.check, changed)
    write_or_check(SRC / "gen_skills.c", skills_c, args.check, changed)

    teams_h, teams_c = gen_teams(teams, known)
    write_or_check(INC / "gen_teams.h", teams_h, args.check, changed)
    write_or_check(SRC / "gen_teams.c", teams_c, args.check, changed)

    tables_h, tables_c = gen_tables(tables)
    write_or_check(INC / "gen_tables.h", tables_h, args.check, changed)
    write_or_check(SRC / "gen_tables.c", tables_c, args.check, changed)

    if args.check and changed:
        print("STALE generated files (run tools/codegen.py):")
        for c in changed:
            print(" ", c)
        sys.exit(1)


if __name__ == "__main__":
    main()
