#!/usr/bin/env bash
# Install the Blood Bowl env and the bloodbowl-rl patch series into a pinned
# PufferLib 5.0 tree (branch 5.0, commit 6ffa5b1, "5.0 Experiments").
#
# Layout written into the 5.0 tree:
#   ocean/bloodbowl/env/              cp -RL of puffer/bloodbowl (source of truth,
#                                     byte-identical; .content_hash = installer hash)
#   ocean/bloodbowl/bloodbowl.h       5.0 ENV_HEADER adapter (training/puffer5/adapter)
#   ocean/bloodbowl/bloodbowl5_env.c  C translation unit wrapping the 4.0 binding.c
#   ocean/bloodbowl/shim/vecenv.h     4.0 vecenv API shim used only by that TU
#   ocean/bloodbowl/bloodbowl5_generated.h   derived constants (Log width, hash)
#   config/bloodbowl.ini              chain 30 recipe (training/puffer5/bloodbowl.ini)
#   src/, build.sh                    training/puffer5/patches/*.patch, in order
#
# Usage: tools/install_puffer5_env.sh PUFFER5_TREE
#        tools/install_puffer5_env.sh --check PUFFER5_TREE
#
# --check is the drift guard: it rebuilds the expected patched files from the
# pinned commit in a temp dir and compares them with the tree, and compares the
# installed env snapshot hash with puffer/bloodbowl. Exit 1 means reinstall
# into a clean pinned checkout.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PIN=6ffa5b10dbbbe4d1e8288367c7d9d3acd3bad4a2
MODE=install
if [ "${1:-}" = "--check" ]; then
    MODE=check
    shift
fi
PUFFER="${1:?usage: tools/install_puffer5_env.sh [--check] PUFFER5_TREE}"
[ -f "$PUFFER/build.sh" ] && [ -f "$PUFFER/src/pufferl.cu" ] || {
    echo "error: $PUFFER is not a PufferLib 5.0 tree" >&2; exit 1; }
PUFFER="$(cd "$PUFFER" && pwd)"

PATCH_DIR="$ROOT/training/puffer5/patches"
ADAPTER="$ROOT/training/puffer5/adapter"
INI="$ROOT/training/puffer5/bloodbowl.ini"
SRC="$ROOT/puffer/bloodbowl"
DST="$PUFFER/ocean/bloodbowl"

if command -v sha256sum >/dev/null 2>&1; then SHA256="sha256sum"; else SHA256="shasum -a 256"; fi
snapshot_hash() {
    (cd "$1" && find -L . -type f ! -name .content_hash -print0 | LC_ALL=C sort -z \
        | xargs -0 $SHA256 | $SHA256 | awk '{print $1}')
}
patch_bundle_hash() {
    # A loop, not xargs: GNU xargs runs the hasher on stdin for an empty list.
    (cd "$PATCH_DIR" && for p in $(ls *.patch 2>/dev/null | LC_ALL=C sort); do
        $SHA256 "$p"
    done | $SHA256 | awk '{print $1}')
}
patches() {
    ls "$PATCH_DIR"/*.patch 2>/dev/null | LC_ALL=C sort || true
}

head_sha="$(git -C "$PUFFER" rev-parse HEAD 2>/dev/null || echo none)"
if [ "$head_sha" != "$PIN" ]; then
    echo "error: $PUFFER HEAD is $head_sha, expected pinned 5.0 commit $PIN" >&2
    exit 1
fi

source_hash="$(snapshot_hash "$SRC")"

# Files the patch series touches, derived from the patch headers.
touched_files() {
    for p in $(patches); do
        sed -n 's#^+++ b/\(.*\)$#\1#p' "$p"
    done | LC_ALL=C sort -u
}

expected_tree() {
    local out="$1"
    git -C "$PUFFER" archive "$PIN" | tar -x -C "$out"
    for p in $(patches); do
        git -C "$out" apply --no-index "$p" 2>/dev/null || (cd "$out" && git apply "$p") || {
            echo "error: patch does not apply to pinned tree: $p" >&2; return 1; }
    done
}

write_generated_header() {
    local probe_dir
    probe_dir="$(mktemp -d)"
    cat > "$probe_dir/probe.c" <<'EOF'
#include <stdio.h>
#include "bloodbowl.h"
int main(void) {
    printf("%d\n", (int)(sizeof(Log) / sizeof(float)));
    return 0;
}
EOF
    "${CC:-cc}" -O0 -w -I"$DST/env" "$probe_dir/probe.c" -o "$probe_dir/probe" -lm
    local nf
    nf="$("$probe_dir/probe")"
    rm -rf "$probe_dir"
    cat > "$DST/bloodbowl5_generated.h" <<EOF
// Generated by tools/install_puffer5_env.sh; do not edit.
#pragma once
#define BBE5_LOG_FLOATS $nf
#define BBE5_ENV_SOURCE_HASH "$source_hash"
#define BBE5_PATCH_BUNDLE_HASH "$(patch_bundle_hash)"
EOF
}

if [ "$MODE" = "install" ]; then
    for p in $(patches); do
        if git -C "$PUFFER" apply --reverse --check "$p" 2>/dev/null; then
            echo "patch already applied: $(basename "$p")"
        else
            git -C "$PUFFER" apply --check "$p" || {
                echo "error: $(basename "$p") does not apply; start from a clean $PIN checkout" >&2
                exit 1; }
            git -C "$PUFFER" apply "$p"
            echo "applied: $(basename "$p")"
        fi
    done
    rm -rf "$DST"
    mkdir -p "$DST/env" "$DST/shim"
    cp -RL "$SRC/." "$DST/env/"
    echo "$source_hash" > "$DST/env/.content_hash"
    cp "$ADAPTER/bloodbowl.h" "$DST/bloodbowl.h"
    cp "$ADAPTER/bloodbowl5_env.c" "$DST/bloodbowl5_env.c"
    cp "$ADAPTER/shim/vecenv.h" "$DST/shim/vecenv.h"
    write_generated_header
    cp "$INI" "$PUFFER/config/bloodbowl.ini"
    echo "installed bloodbowl env: source ${source_hash:0:8}, patch bundle $(patch_bundle_hash | cut -c1-8)"
fi

# --- drift check (also runs after install) -----------------------------------
fail=0
have="$(snapshot_hash "$DST/env" 2>/dev/null || echo none)"
if [ "$have" != "$source_hash" ]; then
    echo "drift check: env snapshot ${have:0:8} != source ${source_hash:0:8}" >&2
    fail=1
fi
for f in bloodbowl.h bloodbowl5_env.c shim/vecenv.h; do
    if ! cmp -s "$ADAPTER/$f" "$DST/$f"; then
        echo "drift check: adapter file differs: $f" >&2
        fail=1
    fi
done
if ! cmp -s "$INI" "$PUFFER/config/bloodbowl.ini"; then
    echo "drift check: config/bloodbowl.ini differs" >&2
    fail=1
fi
if ! grep -Fq "\"$source_hash\"" "$DST/bloodbowl5_generated.h" 2>/dev/null; then
    echo "drift check: bloodbowl5_generated.h missing or stale" >&2
    fail=1
fi
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
if expected_tree "$tmp"; then
    for f in $(touched_files); do
        if ! cmp -s "$tmp/$f" "$PUFFER/$f"; then
            echo "drift check: patched file differs from pinned series: $f" >&2
            fail=1
        fi
    done
else
    fail=1
fi
if [ "$fail" -ne 0 ]; then
    echo "drift check: FAILED" >&2
    exit 1
fi
echo "drift check: OK (${source_hash:0:8} patch bundle $(patch_bundle_hash | cut -c1-8))"
