// gen_teams.c — GENERATED by tools/codegen.py from engine/data/spec/. DO NOT EDIT.
// spec-hash: d2181fd18e8383e0
#include "bb/gen_teams.h"

const bb_team_def bb_team_defs[BB_TEAM_COUNT] = {
    { // Amazon
        "amazon", "Amazon", 1, 60, 1, 4,
        {
            {"Eagle Warrior", 0, 16, 50, 6, 3, 3, 4, 8, 1, {BB_SK_DODGE, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 6, 0},
            {"Python Warrior", 0, 2, 80, 6, 3, 3, 3, 8, 4, {BB_SK_DODGE, BB_SK_ON_THE_BALL, BB_SK_PASS, BB_SK_SAFE_PASS, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Piranha Warrior", 0, 2, 90, 7, 3, 3, 4, 8, 3, {BB_SK_DODGE, BB_SK_HIT_AND_RUN, BB_SK_JUMP_UP, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Jaguar Warrior", 0, 2, 110, 6, 4, 3, 4, 9, 2, {BB_SK_DEFENSIVE, BB_SK_DODGE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
        },
    },
    { // Black Orc
        "black_orc", "Black Orc", 3, 60, 1, 3,
        {
            {"Goblin Bruiser", 0, 16, 45, 6, 2, 3, 4, 8, 4, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 13, 0},
            {"Black Orc", 0, 6, 90, 4, 4, 4, 5, 10, 2, {BB_SK_BRAWLER, BB_SK_GRAB, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Trained Troll", 0, 1, 115, 4, 5, 5, 5, 10, 6, {BB_SK_ALWAYS_HUNGRY, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Bretonnian
        "bretonnian", "Bretonnian", 2, 60, 1, 4,
        {
            {"Bretonnian Squire", 0, 16, 50, 6, 3, 3, 4, 8, 1, {BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 6, 0},
            {"Bretonnian Knight Catcher", 0, 2, 85, 7, 3, 3, 4, 9, 3, {BB_SK_CATCH, BB_SK_DAUNTLESS, BB_SK_NERVES_OF_STEEL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Bretonnian Knight Thrower", 0, 2, 80, 6, 3, 3, 3, 9, 3, {BB_SK_DAUNTLESS, BB_SK_NERVES_OF_STEEL, BB_SK_PASS, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Grail Knight", 0, 2, 95, 7, 3, 3, 4, 10, 3, {BB_SK_BLOCK, BB_SK_DAUNTLESS, BB_SK_STEADY_FOOTING, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
        },
    },
    { // Chaos Chosen
        "chaos_chosen", "Chaos Chosen", 3, 50, 1, 5,
        {
            {"Beastman Lineman", 0, 16, 55, 6, 3, 3, 3, 9, 2, {BB_SK_HORNS, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 17, 46, 0},
            {"Chaos Chosen", 0, 4, 100, 5, 4, 3, 5, 10, 1, {BB_SK_ARM_BAR, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 34, 0},
            {"Troll", 0, 1, 115, 4, 5, 5, 5, 10, 7, {BB_SK_ALWAYS_HUNGRY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 20, 11, 1},
            {"Ogre", 0, 1, 140, 5, 5, 4, 5, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 20, 3, 1},
            {"Minotaur", 0, 1, 150, 5, 5, 4, 6, 9, 6, {BB_SK_FRENZY, BB_SK_HORNS, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_UNCHANNELLED_FURY, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 20, 3, 1},
        },
    },
    { // Chaos Dwarf
        "chaos_dwarf", "Chaos Dwarf", 1, 70, 1, 6,
        {
            {"Hobgoblin Lineman", 0, 16, 40, 6, 3, 3, 4, 8, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 32, 7, 0},
            {"Sneaky Stabba", 0, 2, 60, 6, 3, 3, 5, 8, 2, {BB_SK_SHADOWING, BB_SK_STAB, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 6, 0},
            {"Chaos Dwarf Blocker", 0, 4, 70, 4, 3, 4, 6, 10, 3, {BB_SK_BLOCK, BB_SK_IRON_HARD_SKIN, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 50, 0},
            {"Flamesmith", 0, 2, 80, 5, 3, 4, 6, 10, 4, {BB_SK_BRAWLER, BB_SK_BREATHE_FIRE, BB_SK_DISTURBING_PRESENCE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 50, 0},
            {"Bull Centaur", 0, 2, 130, 6, 4, 4, 6, 10, 4, {BB_SK_SPRINT, BB_SK_SURE_FEET, BB_SK_THICK_SKULL, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 50, 0},
            {"Minotaur", 0, 1, 150, 5, 5, 4, 6, 9, 6, {BB_SK_FRENZY, BB_SK_HORNS, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_UNCHANNELLED_FURY, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 20, 3, 1},
        },
    },
    { // Chaos Renegades
        "chaos_renegades", "Chaos Renegades", 3, 70, 1, 10,
        {
            {"Renegade Human", 0, 16, 50, 6, 3, 3, 4, 9, 1, {BB_SK_ANIMOSITY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 49, 6, 0},
            {"Renegade Goblin", 0, 1, 40, 6, 2, 3, 4, 8, 4, {BB_SK_ANIMOSITY, BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 50, 9, 0},
            {"Renegade Orc", 0, 1, 50, 5, 3, 3, 4, 10, 1, {BB_SK_ANIMOSITY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 49, 6, 0},
            {"Renegade Skaven", 0, 1, 50, 7, 3, 3, 4, 8, 1, {BB_SK_ANIMOSITY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 49, 6, 0},
            {"Renegade Dark Elf", 0, 1, 65, 6, 3, 2, 3, 9, 1, {BB_SK_ANIMOSITY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 51, 4, 0},
            {"Renegade Human Thrower", 0, 1, 75, 6, 3, 3, 3, 9, 3, {BB_SK_ANIMOSITY, BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 57, 6, 0},
            {"Troll", 0, 1, 115, 4, 5, 5, 5, 10, 7, {BB_SK_ALWAYS_HUNGRY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 27, 1},
            {"Ogre", 0, 1, 140, 5, 5, 4, 5, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0}, {-1, 3, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 19, 1},
            {"Minotaur", 0, 1, 150, 5, 5, 4, 6, 9, 6, {BB_SK_FRENZY, BB_SK_HORNS, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_UNCHANNELLED_FURY, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 4, 19, 1},
            {"Rat Ogre", 0, 1, 150, 6, 5, 4, 6, 9, 5, {BB_SK_ANIMAL_SAVAGERY, BB_SK_FRENZY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PREHENSILE_TAIL, 0, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 4, 19, 1},
        },
    },
    { // Dark Elf
        "dark_elf", "Dark Elf", 1, 50, 1, 5,
        {
            {"Dark Elf Lineman", 0, 16, 65, 6, 3, 2, 3, 9, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 36, 0},
            {"Dark Elf Runner", 0, 2, 80, 7, 3, 2, 3, 8, 2, {BB_SK_DUMP_OFF, BB_SK_PUNT, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 36, 0},
            {"Dark Elf Assassin", 0, 2, 90, 7, 3, 2, 4, 8, 3, {BB_SK_HIT_AND_RUN, BB_SK_SHADOWING, BB_SK_STAB, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 5, 0},
            {"Dark Elf Blitzer", 0, 2, 105, 7, 3, 2, 3, 9, 1, {BB_SK_BLOCK, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 44, 0},
            {"Witch Elf", 0, 2, 110, 7, 3, 2, 4, 8, 3, {BB_SK_DODGE, BB_SK_FRENZY, BB_SK_JUMP_UP, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 36, 0},
        },
    },
    { // Dwarf
        "dwarf", "Dwarf", 2, 60, 1, 5,
        {
            {"Dwarf Lineman", 0, 16, 70, 4, 3, 4, 5, 10, 3, {BB_SK_BLOCK, BB_SK_DEFENSIVE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 4, 0},
            {"Dwarf Runner", 0, 2, 80, 6, 3, 3, 4, 9, 3, {BB_SK_SPRINT, BB_SK_SURE_HANDS, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Dwarf Blitzer", 0, 2, 100, 5, 3, 4, 4, 10, 4, {BB_SK_BLOCK, BB_SK_DIVING_TACKLE, BB_SK_TACKLE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 8, 0},
            {"Troll Slayer", 0, 2, 95, 5, 3, 4, 5, 9, 5, {BB_SK_BLOCK, BB_SK_DAUNTLESS, BB_SK_FRENZY, BB_SK_HATRED, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 32, 0},
            {"Deathroller", 0, 1, 170, 5, 7, 5, 0, 11, 8, {BB_SK_BREAK_TACKLE, BB_SK_DIRTY_PLAYER, BB_SK_JUGGERNAUT, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_NO_BALL, BB_SK_SECRET_WEAPON, BB_SK_STAND_FIRM, 0, 0}, {-1, -1, -1, 4, -1, -1, -1, -1, -1, -1}, 36, 1, 1},
        },
    },
    { // Elven Union
        "elven_union", "Elven Union", 2, 50, 1, 4,
        {
            {"Elf Lineman", 0, 16, 65, 6, 3, 2, 3, 8, 1, {BB_SK_FUMBLEROOSKI, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Elf Thrower", 0, 2, 75, 6, 3, 2, 2, 8, 2, {BB_SK_HAIL_MARY_PASS, BB_SK_PASS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 4, 0},
            {"Elf Catcher", 0, 2, 100, 8, 3, 2, 4, 8, 3, {BB_SK_CATCH, BB_SK_DIVING_CATCH, BB_SK_NERVES_OF_STEEL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Elf Blitzer", 0, 2, 115, 7, 3, 2, 3, 9, 2, {BB_SK_BLOCK, BB_SK_SIDESTEP, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
        },
    },
    { // Gnome
        "gnome", "Gnome", 4, 50, 1, 5,
        {
            {"Gnome Lineman", 0, 16, 40, 5, 2, 3, 4, 7, 4, {BB_SK_JUMP_UP, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Woodland Fox", 0, 2, 50, 7, 2, 2, 0, 6, 4, {BB_SK_DODGE, BB_SK_MY_BALL, BB_SK_SIDESTEP, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 0, 2, 0},
            {"Gnome Illusionist", 0, 2, 50, 5, 2, 3, 3, 7, 4, {BB_SK_JUMP_UP, BB_SK_STUNTY, BB_SK_TRICKSTER, BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 10, 33, 0},
            {"Gnome Beastmaster", 0, 2, 55, 5, 2, 3, 4, 8, 4, {BB_SK_GUARD, BB_SK_JUMP_UP, BB_SK_STUNTY, BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Altern Forest Treeman", 0, 2, 120, 2, 6, 5, 5, 11, 7, {BB_SK_MIGHTY_BLOW, BB_SK_STAND_FIRM, BB_SK_STRONG_ARM, BB_SK_TAKE_ROOT, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, BB_SK_TIMMM_BER, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Goblin
        "goblin", "Goblin", 4, 60, 1, 8,
        {
            {"Goblin Lineman", 0, 16, 40, 6, 2, 3, 4, 8, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 13, 0},
            {"Looney", 0, 1, 40, 6, 2, 3, 0, 8, 4, {BB_SK_CHAINSAW, BB_SK_NO_BALL, BB_SK_SECRET_WEAPON, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 32, 7, 0},
            {"Bomma", 0, 1, 45, 6, 2, 3, 4, 8, 4, {BB_SK_BOMBARDIER, BB_SK_DODGE, BB_SK_SECRET_WEAPON, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 40, 7, 0},
            {"'Ooligan", 0, 1, 60, 6, 2, 3, 5, 8, 6, {BB_SK_DIRTY_PLAYER, BB_SK_DISTURBING_PRESENCE, BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, BB_SK_TAUNT, 0, 0, 0, 0}, {1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 5, 0},
            {"Doom Diver", 0, 1, 65, 6, 2, 3, 6, 8, 4, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, BB_SK_SWOOP, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Fanatic", 0, 1, 70, 3, 7, 3, 0, 8, 4, {BB_SK_BALL_AND_CHAIN, BB_SK_NO_BALL, BB_SK_SECRET_WEAPON, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 36, 3, 0},
            {"Pogoer", 0, 1, 75, 7, 2, 3, 4, 8, 3, {BB_SK_DODGE, BB_SK_POGO, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Trained Troll", 0, 2, 115, 4, 5, 5, 5, 10, 6, {BB_SK_ALWAYS_HUNGRY, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Halfling
        "halfling", "Halfling", 4, 60, 1, 4,
        {
            {"Halfling Hopeful", 0, 16, 30, 5, 2, 3, 4, 7, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Halfling Hefty", 0, 2, 50, 5, 2, 3, 3, 8, 3, {BB_SK_DODGE, BB_SK_FEND, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 10, 37, 0},
            {"Halfling Catcher", 0, 2, 55, 5, 2, 3, 4, 7, 5, {BB_SK_CATCH, BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_SPRINT, BB_SK_STUNTY, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Athel Forest Treeman", 0, 2, 120, 2, 6, 5, 5, 11, 7, {BB_SK_MIGHTY_BLOW, BB_SK_STAND_FIRM, BB_SK_STRONG_ARM, BB_SK_TAKE_ROOT, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, BB_SK_TIMMM_BER, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 43, 1},
        },
    },
    { // High Elf
        "high_elf", "High Elf", 1, 50, 1, 4,
        {
            {"High Elf Lineman", 0, 16, 65, 6, 3, 2, 3, 9, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Phoenix Warrior", 0, 2, 90, 6, 3, 2, 2, 9, 3, {BB_SK_CLOUD_BURSTER, BB_SK_PASS, BB_SK_SAFE_PASS, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 4, 0},
            {"Dragon Prince", 0, 2, 110, 8, 3, 2, 4, 9, 3, {BB_SK_BLOCK, BB_SK_MY_BALL, BB_SK_STEADY_FOOTING, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"White Lion", 0, 2, 110, 7, 3, 2, 3, 9, 2, {BB_SK_CLAWS, BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
        },
    },
    { // Human
        "human", "Human", 2, 50, 1, 6,
        {
            {"Human Lineman", 0, 16, 50, 6, 3, 3, 4, 9, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 38, 0},
            {"Halfling Hopeful", 0, 3, 30, 5, 2, 3, 4, 7, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 37, 0},
            {"Human Catcher", 0, 2, 75, 8, 3, 3, 4, 8, 2, {BB_SK_CATCH, BB_SK_DODGE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 44, 0},
            {"Human Thrower", 0, 2, 75, 6, 3, 3, 3, 9, 2, {BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 38, 0},
            {"Human Blitzer", 0, 2, 85, 7, 3, 3, 4, 9, 2, {BB_SK_BLOCK, BB_SK_TACKLE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Ogre", 0, 1, 140, 5, 5, 4, 5, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0}, {-1, 3, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Imperial Nobility
        "imperial_nobility", "Imperial Nobility", 2, 60, 1, 5,
        {
            {"Imperial Retainer", 0, 16, 45, 6, 3, 3, 4, 8, 1, {BB_SK_FEND, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 6, 0},
            {"Imperial Thrower", 0, 2, 75, 6, 3, 3, 2, 9, 3, {BB_SK_GIVE_AND_GO, BB_SK_PASS, BB_SK_PRO, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Bodyguard", 0, 4, 85, 5, 3, 3, 4, 9, 2, {BB_SK_STAND_FIRM, BB_SK_WRESTLE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
            {"Noble Blitzer", 0, 2, 90, 7, 3, 3, 4, 9, 3, {BB_SK_BLOCK, BB_SK_CATCH, BB_SK_PRO, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
            {"Ogre", 0, 1, 140, 5, 5, 4, 5, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0}, {-1, 3, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Khorne
        "khorne", "Khorne", 3, 60, 1, 4,
        {
            {"Bloodborn Marauder", 0, 16, 50, 6, 3, 3, 4, 8, 1, {BB_SK_FRENZY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 17, 38, 0},
            {"Khorngor", 0, 2, 70, 6, 3, 3, 4, 9, 4, {BB_SK_HORNS, BB_SK_JUGGERNAUT, BB_SK_JUMP_UP, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 42, 0},
            {"Bloodseeker", 0, 4, 105, 5, 4, 4, 6, 10, 1, {BB_SK_FRENZY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 34, 0},
            {"Bloodspawn", 0, 1, 160, 5, 5, 4, 6, 9, 5, {BB_SK_CLAWS, BB_SK_FRENZY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_UNCHANNELLED_FURY, 0, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 20, 3, 1},
        },
    },
    { // Lizardmen
        "lizardmen", "Lizardmen", 1, 70, 1, 4,
        {
            {"Skink Lineman", 0, 16, 60, 8, 2, 3, 4, 8, 2, {BB_SK_DODGE, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 45, 0},
            {"Chameleon Skink", 0, 2, 70, 7, 2, 3, 3, 8, 4, {BB_SK_DODGE, BB_SK_ON_THE_BALL, BB_SK_SHADOWING, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 10, 37, 0},
            {"Saurus Blocker", 0, 6, 90, 6, 4, 5, 6, 10, 2, {BB_SK_JUGGERNAUT, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
            {"Kroxigor", 0, 1, 140, 6, 5, 5, 6, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PREHENSILE_TAIL, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Necromantic Horror
        "necromantic_horror", "Necromantic Horror", 2, 70, 0, 5,
        {
            {"Zombie Lineman", 0, 16, 40, 4, 3, 4, 6, 9, 3, {BB_SK_EYE_GOUGE, BB_SK_REGENERATION, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 6, 0},
            {"Ghoul Runner", 0, 2, 75, 7, 3, 3, 3, 8, 2, {BB_SK_DODGE, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 44, 0},
            {"Wraith", 0, 2, 85, 6, 3, 3, 0, 9, 5, {BB_SK_BLOCK, BB_SK_FOUL_APPEARANCE, BB_SK_NO_BALL, BB_SK_REGENERATION, BB_SK_SIDESTEP, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Flesh Golem", 0, 2, 110, 4, 4, 4, 6, 10, 4, {BB_SK_REGENERATION, BB_SK_STAND_FIRM, BB_SK_THICK_SKULL, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Werewolf", 0, 2, 120, 8, 3, 3, 3, 9, 3, {BB_SK_CLAWS, BB_SK_FRENZY, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 44, 0},
        },
    },
    { // Norse
        "norse", "Norse", 1, 60, 1, 6,
        {
            {"Norse Raider", 0, 16, 50, 6, 3, 3, 4, 8, 4, {BB_SK_BLOCK, BB_SK_DRUNKARD, BB_SK_THICK_SKULL, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 14, 0},
            {"Beer Boar", 0, 2, 20, 5, 1, 3, 0, 6, 5, {BB_SK_DODGE, BB_SK_NO_BALL, BB_SK_PICK_ME_UP, BB_SK_STUNTY, BB_SK_TITCHY, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 0, 2, 0},
            {"Norse Berserker", 0, 2, 90, 6, 3, 3, 5, 8, 3, {BB_SK_BLOCK, BB_SK_FRENZY, BB_SK_JUMP_UP, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 10, 0},
            {"Valkyrie", 0, 2, 95, 7, 3, 3, 3, 8, 4, {BB_SK_CATCH, BB_SK_DAUNTLESS, BB_SK_PASS, BB_SK_STRIP_BALL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 4, 0},
            {"Ulfwerener", 0, 2, 105, 6, 4, 4, 6, 9, 2, {BB_SK_FRENZY, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
            {"Yhetee", 0, 1, 140, 5, 5, 4, 6, 9, 5, {BB_SK_CLAWS, BB_SK_DISTURBING_PRESENCE, BB_SK_FRENZY, BB_SK_LONER, BB_SK_UNCHANNELLED_FURY, 0, 0, 0, 0, 0}, {-1, -1, -1, 4, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Nurgle
        "nurgle", "Nurgle", 3, 60, 0, 4,
        {
            {"Rotter", 0, 16, 40, 5, 3, 4, 6, 9, 2, {BB_SK_DECAY, BB_SK_PLAGUE_RIDDEN, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 49, 6, 0},
            {"Pestigor", 0, 2, 70, 6, 3, 3, 4, 9, 5, {BB_SK_HORNS, BB_SK_PLAGUE_RIDDEN, BB_SK_REGENERATION, BB_SK_STEADY_FOOTING, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 42, 0},
            {"Bloater", 0, 4, 110, 4, 4, 4, 6, 10, 6, {BB_SK_DISTURBING_PRESENCE, BB_SK_FOUL_APPEARANCE, BB_SK_PLAGUE_RIDDEN, BB_SK_REGENERATION, BB_SK_STAND_FIRM, BB_SK_UNSTEADY, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 34, 0},
            {"Rotspawn", 0, 1, 140, 4, 5, 5, 6, 10, 9, {BB_SK_DISTURBING_PRESENCE, BB_SK_FOUL_APPEARANCE, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PICK_ME_UP, BB_SK_PLAGUE_RIDDEN, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_TENTACLES, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 4, 49, 1},
        },
    },
    { // Ogre
        "ogre", "Ogre", 4, 70, 1, 3,
        {
            {"Gnoblar Lineman", 0, 16, 15, 5, 1, 3, 4, 6, 5, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_SIDESTEP, BB_SK_STUNTY, BB_SK_TITCHY, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 1, 0},
            {"Ogre Blocker", 0, 5, 140, 5, 5, 4, 5, 10, 4, {BB_SK_BONE_HEAD, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 43, 1},
            {"Ogre Runt Punter", 0, 1, 145, 5, 5, 4, 4, 10, 4, {BB_SK_BONE_HEAD, BB_SK_KICK_TEAM_MATE, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 12, 35, 1},
        },
    },
    { // Old World Alliance
        "old_world_alliance", "Old World Alliance", 1, 70, 1, 11,
        {
            {"Human Lineman", 0, 16, 50, 6, 3, 3, 4, 9, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 6, 0},
            {"Halfling Hopeful", 0, 3, 30, 5, 2, 3, 4, 7, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 2, 5, 0},
            {"Human Catcher", 0, 1, 75, 8, 3, 3, 4, 8, 2, {BB_SK_CATCH, BB_SK_DODGE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
            {"Dwarf Lineman", 0, 3, 70, 4, 3, 4, 5, 10, 3, {BB_SK_BLOCK, BB_SK_DEFENSIVE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 4, 0},
            {"Human Thrower", 0, 1, 75, 6, 3, 3, 3, 9, 2, {BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Dwarf Runner", 0, 1, 80, 6, 3, 3, 4, 9, 3, {BB_SK_SPRINT, BB_SK_SURE_HANDS, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 6, 0},
            {"Human Blitzer", 0, 1, 85, 7, 3, 3, 4, 9, 2, {BB_SK_BLOCK, BB_SK_TACKLE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
            {"Dwarf Blitzer", 0, 1, 100, 5, 3, 4, 4, 10, 4, {BB_SK_BLOCK, BB_SK_DIVING_TACKLE, BB_SK_TACKLE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 8, 0},
            {"Troll Slayer", 0, 1, 95, 5, 3, 4, 5, 9, 5, {BB_SK_BLOCK, BB_SK_DAUNTLESS, BB_SK_FRENZY, BB_SK_HATRED, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 2, 0},
            {"Ogre", 0, 1, 140, 5, 5, 4, 5, 10, 5, {BB_SK_BONE_HEAD, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0, 0}, {-1, 3, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
            {"Altern Forest Treeman", 0, 1, 120, 2, 6, 5, 5, 11, 8, {BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_STAND_FIRM, BB_SK_STRONG_ARM, BB_SK_TAKE_ROOT, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, BB_SK_TIMMM_BER, 0, 0}, {4, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Orc
        "orc", "Orc", 2, 60, 1, 6,
        {
            {"Orc Lineman", 0, 16, 50, 5, 3, 3, 4, 10, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Goblin Lineman", 0, 4, 40, 6, 2, 3, 4, 8, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 13, 0},
            {"Orc Thrower", 0, 2, 75, 6, 3, 3, 3, 9, 2, {BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 38, 0},
            {"Orc Blitzer", 0, 2, 85, 6, 3, 3, 4, 10, 2, {BB_SK_BLOCK, BB_SK_BREAK_TACKLE, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Big Un Blocker", 0, 2, 95, 5, 4, 4, 6, 10, 4, {BB_SK_MIGHTY_BLOW, BB_SK_TAUNT, BB_SK_THICK_SKULL, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Troll", 0, 1, 115, 4, 5, 5, 5, 10, 7, {BB_SK_ALWAYS_HUNGRY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Shambling Undead
        "shambling_undead", "Shambling Undead", 2, 70, 0, 5,
        {
            {"Skeleton Lineman", 0, 16, 40, 5, 3, 4, 6, 8, 2, {BB_SK_REGENERATION, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 38, 0},
            {"Zombie Lineman", 0, 16, 40, 4, 3, 4, 6, 9, 3, {BB_SK_EYE_GOUGE, BB_SK_REGENERATION, BB_SK_UNSTEADY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 6, 0},
            {"Ghoul Runner", 0, 2, 75, 7, 3, 3, 3, 8, 2, {BB_SK_DODGE, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 44, 0},
            {"Wight Blitzer", 0, 2, 95, 6, 3, 3, 5, 9, 4, {BB_SK_BLOCK, BB_SK_REGENERATION, BB_SK_TACKLE, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Mummy", 0, 2, 125, 3, 5, 5, 6, 10, 2, {BB_SK_MIGHTY_BLOW, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Skaven
        "skaven", "Skaven", 2, 50, 1, 5,
        {
            {"Skaven Clanrat", 0, 16, 50, 7, 3, 3, 4, 8, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 33, 22, 0},
            {"Skaven Thrower", 0, 2, 80, 7, 3, 3, 2, 8, 2, {BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 54, 0},
            {"Gutter Runner", 0, 2, 85, 9, 2, 2, 4, 8, 2, {BB_SK_DODGE, BB_SK_STAB, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 35, 20, 0},
            {"Skaven Blitzer", 0, 2, 90, 8, 3, 3, 4, 9, 2, {BB_SK_BLOCK, BB_SK_STRIP_BALL, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 50, 0},
            {"Rat Ogre", 0, 1, 150, 6, 5, 4, 6, 9, 5, {BB_SK_ANIMAL_SAVAGERY, BB_SK_FRENZY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PREHENSILE_TAIL, 0, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 4, 19, 1},
        },
    },
    { // Snotling
        "snotling", "Snotling", 4, 70, 1, 6,
        {
            {"Snotling Lineman", 0, 16, 15, 5, 1, 3, 4, 6, 6, {BB_SK_DODGE, BB_SK_INSIGNIFICANT, BB_SK_RIGHT_STUFF, BB_SK_SIDESTEP, BB_SK_STUNTY, BB_SK_TITCHY, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 1, 0},
            {"Fun-hoppa", 0, 2, 20, 6, 1, 3, 4, 6, 5, {BB_SK_DODGE, BB_SK_POGO, BB_SK_RIGHT_STUFF, BB_SK_SIDESTEP, BB_SK_STUNTY, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 1, 0},
            {"Stilty Runna", 0, 2, 20, 6, 1, 3, 4, 6, 5, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_SIDESTEP, BB_SK_SPRINT, BB_SK_STUNTY, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 34, 1, 0},
            {"Fungus Flinga", 0, 2, 30, 5, 1, 3, 4, 6, 7, {BB_SK_BOMBARDIER, BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_SECRET_WEAPON, BB_SK_SIDESTEP, BB_SK_STUNTY, BB_SK_TITCHY, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 42, 1, 0},
            {"Pump Wagon", 0, 2, 100, 5, 5, 5, 6, 9, 5, {BB_SK_DIRTY_PLAYER, BB_SK_JUGGERNAUT, BB_SK_MIGHTY_BLOW, BB_SK_REALLY_STUPID, BB_SK_STAND_FIRM, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 36, 3, 1},
            {"Trained Troll", 0, 2, 115, 4, 5, 5, 5, 10, 6, {BB_SK_ALWAYS_HUNGRY, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 11, 1},
        },
    },
    { // Tomb Kings
        "tomb_kings", "Tomb Kings", 2, 60, 0, 4,
        {
            {"Skeleton Lineman", 0, 16, 40, 5, 3, 4, 6, 8, 2, {BB_SK_REGENERATION, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 38, 0},
            {"Tomb Kings Thrower", 0, 2, 65, 6, 3, 4, 3, 9, 4, {BB_SK_PASS, BB_SK_REGENERATION, BB_SK_SURE_HANDS, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 9, 38, 0},
            {"Tomb Kings Blitzer", 0, 2, 85, 6, 3, 4, 5, 9, 3, {BB_SK_BLOCK, BB_SK_REGENERATION, BB_SK_THICK_SKULL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 5, 34, 0},
            {"Tomb Guardian", 0, 4, 115, 4, 5, 5, 6, 10, 3, {BB_SK_BRAWLER, BB_SK_DECAY, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Underworld Denizens
        "underworld_denizens", "Underworld Denizens", 1, 70, 1, 8,
        {
            {"Goblin Lineman", 0, 16, 40, 6, 2, 3, 4, 8, 3, {BB_SK_DODGE, BB_SK_RIGHT_STUFF, BB_SK_STUNTY, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 50, 13, 0},
            {"Snotling Lineman", 0, 6, 15, 5, 1, 3, 4, 6, 6, {BB_SK_DODGE, BB_SK_INSIGNIFICANT, BB_SK_RIGHT_STUFF, BB_SK_SIDESTEP, BB_SK_STUNTY, BB_SK_TITCHY, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 50, 1, 0},
            {"Skaven Clanrat", 0, 3, 50, 7, 3, 3, 4, 8, 1, {BB_SK_ANIMOSITY, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 49, 6, 0},
            {"Skaven Thrower", 0, 1, 80, 7, 3, 3, 2, 8, 3, {BB_SK_ANIMOSITY, BB_SK_PASS, BB_SK_SURE_HANDS, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 25, 38, 0},
            {"Gutter Runner", 0, 1, 85, 9, 2, 2, 4, 8, 3, {BB_SK_ANIMOSITY, BB_SK_DODGE, BB_SK_STAB, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 51, 4, 0},
            {"Skaven Blitzer", 0, 1, 90, 8, 3, 3, 4, 9, 3, {BB_SK_ANIMOSITY, BB_SK_BLOCK, BB_SK_STRIP_BALL, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 21, 10, 0},
            {"Troll", 0, 1, 115, 4, 5, 5, 5, 10, 7, {BB_SK_ALWAYS_HUNGRY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PROJECTILE_VOMIT, BB_SK_REALLY_STUPID, BB_SK_REGENERATION, BB_SK_THROW_TEAM_MATE, 0, 0, 0}, {-1, 4, -1, -1, -1, -1, -1, -1, -1, -1}, 20, 11, 1},
            {"Rat Ogre", 0, 1, 150, 6, 5, 4, 6, 9, 5, {BB_SK_ANIMAL_SAVAGERY, BB_SK_FRENZY, BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_PREHENSILE_TAIL, 0, 0, 0, 0, 0}, {-1, -1, 4, -1, -1, -1, -1, -1, -1, -1}, 20, 3, 1},
        },
    },
    { // Vampire
        "vampire", "Vampire", 2, 60, 1, 5,
        {
            {"Thrall Lineman", 0, 16, 40, 6, 3, 3, 4, 8, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 1, 6, 0},
            {"Vampire Runner", 0, 2, 100, 8, 3, 2, 3, 8, 3, {BB_SK_BLOODLUST, BB_SK_HYPNOTIC_GAZE, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0, 0}, {2, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
            {"Vampire Thrower", 0, 2, 110, 6, 4, 2, 2, 9, 4, {BB_SK_BLOODLUST, BB_SK_HYPNOTIC_GAZE, BB_SK_PASS, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0}, {2, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 4, 0},
            {"Vampire Blitzer", 0, 2, 110, 6, 4, 2, 4, 9, 4, {BB_SK_BLOODLUST, BB_SK_HYPNOTIC_GAZE, BB_SK_JUGGERNAUT, BB_SK_REGENERATION, 0, 0, 0, 0, 0, 0}, {3, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 7, 0, 0},
            {"Vargheist", 0, 1, 150, 5, 5, 4, 6, 10, 5, {BB_SK_BLOODLUST, BB_SK_CLAWS, BB_SK_FRENZY, BB_SK_LONER, BB_SK_REGENERATION, 0, 0, 0, 0, 0}, {3, -1, -1, 4, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
    { // Wood Elf
        "wood_elf", "Wood Elf", 1, 50, 1, 5,
        {
            {"Wood Elf Lineman", 0, 16, 65, 7, 3, 2, 4, 8, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 4, 0},
            {"Wood Elf Thrower", 0, 2, 85, 7, 3, 2, 2, 8, 2, {BB_SK_PASS, BB_SK_SAFE_PAIR_OF_HANDS, 0, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 11, 4, 0},
            {"Wood Elf Catcher", 0, 2, 90, 8, 2, 2, 3, 8, 3, {BB_SK_CATCH, BB_SK_DODGE, BB_SK_SPRINT, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
            {"Wardancer", 0, 2, 130, 8, 3, 2, 3, 8, 3, {BB_SK_BLOCK, BB_SK_DODGE, BB_SK_LEAP, 0, 0, 0, 0, 0, 0, 0}, {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 3, 12, 0},
            {"Loren Forest Treeman", 0, 1, 120, 2, 6, 5, 5, 11, 7, {BB_SK_LONER, BB_SK_MIGHTY_BLOW, BB_SK_STAND_FIRM, BB_SK_STRONG_ARM, BB_SK_TAKE_ROOT, BB_SK_THICK_SKULL, BB_SK_THROW_TEAM_MATE, 0, 0, 0}, {4, -1, -1, -1, -1, -1, -1, -1, -1, -1}, 4, 3, 1},
        },
    },
};
